### ISSUE TITLE
[BUG] TIFFTAG_SAMPLEFORMAT not specified

### ISSUE THREAD

**Issue by elgw** [ggirelli/radiantkit#46]
The tag `TIFFTAG_SAMPLEFORMAT` not specified in the exported tiff files when using 
```
radiant nd2_to_tiff
```

Please use either `SAMPLEFORMAT_UINT` for unsigned integers.

(The other option is `SAMPLEFORMAT_IEEEFP` for floats.)

**Comment by ggirelli** [comment]
Note for myself (from `tifffile.TiffWriter.write` docs):

     |      extratags : sequence of tuples
     |          Additional tags as [(code, dtype, count, value, writeonce)].
     |      
     |          code : int
     |              The TIFF tag Id.
     |          dtype : str
     |              Data type of items in 'value' in Python struct format.
     |              One of B, s, H, I, 2I, b, h, i, 2i, f, d, Q, or q.
     |          count : int
     |              Number of data values. Not used for string or bytes values.
     |          value : sequence
     |              'Count' values compatible with 'dtype'.
     |              Bytes must contain count values of dtype packed as binary data.
     |          writeonce : bool
     |              If True, the tag is written to the first page of a contiguous

**Comment by ggirelli** [comment]
The current implementation of `nd2_to_tiff` extrapolates `dtype` from the maximum value in the field of view (Z-stack), as read by `ND2Reader`. I.e.,

```python
imt.get_dtype(field_of_view.max())
```

An `extratag` can be added accordingly:

* `SAMPLEFORMAT_UINT` for unsigned integers
* `SAMPLEFORMAT_IEEEFP` for floats

**Comment by ggirelli** [comment]
Details here: https://www.awaresystems.be/imaging/tiff/tifftags/sampleformat.html

**Comment by ggirelli** [comment]
Currently using `tifffile=^2020.10.1`, where `The SampleFormat tag is derived from the data type or dtype.`

**Comment by ggirelli** [comment]
This should now be fixed in the `dev` branch. I will now close the issue. Please double-check and re-open if the output is not as expected.

**Comment by ggirelli** [comment]
Should not use the `extratag` option. Instead, impose conversion of pims frame read by `nd2reader` based on `SAMPLEFORMAT` and `BITSPERSAMPLE` tags that need to be parsed from the nd2 metadata.

**Comment by ggirelli** [comment]
Now fixed in `v0.0.1.16Nov2020` (merged to `main` branch). Supports natively nd2 files described as `uint`, `int`, or `float` with a bit-depth of `8`, `16`, or `32`. Any other definition is specified as `float64` in the output.
